# Generated by Django 2.0.1 on 2018-01-18 18:07

from django.db import migrations


def create_subjects(apps, schema_editor):
    Subject = apps.get_model('classroom', 'Subject')
    Subject.objects.create(departement='Informatique',annee='M1',specialite='SSI',section='A', color='#343a40')
    Subject.objects.create(departement='Informatique',annee='M1',specialite='SII',section='A', color='#007bff')
    Subject.objects.create(departement='Informatique',annee='M1',specialite='MIV',section='A', color='#28a745')
    Subject.objects.create(departement='Informatique',annee='M1',specialite='IL',section='A',color='#17a2b8')
    Subject.objects.create(departement='Informatique',annee='M1',specialite='RSD',section='A', color='#ffc107')
    Subject.objects.create(departement='Informatique',annee='M1',specialite='BIO_INF',section='A', color='#F2F2F2')

class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_subjects),
    ]
