# Generated by Django 3.0.5 on 2020-04-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_create_initial_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='quiz',
        ),
    ]
