# Generated by Django 3.0.5 on 2020-04-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_remove_studentanswer_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rep_to', to='classroom.Quiz'),
            preserve_default=False,
        ),
    ]
