# Generated by Django 3.0.5 on 2020-04-04 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_studentanswer_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers_to', to='classroom.Question'),
            preserve_default=False,
        ),
    ]
