# Generated by Django 3.0.5 on 2020-04-04 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_studentanswer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_to', to='classroom.Question'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rep_to', to='classroom.Quiz'),
        ),
    ]
