# Generated by Django 3.0.5 on 2020-04-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20200404_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='matricule',
            field=models.CharField(default=161631097303, max_length=12, verbose_name='Matricule'),
            preserve_default=False,
        ),
    ]
