# Generated by Django 3.0.5 on 2020-04-22 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_student_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='quiz',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='ans', to='classroom.Quiz'),
            preserve_default=False,
        ),
    ]
