# Generated by Django 3.0.5 on 2020-04-22 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_remove_studentanswer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stuanswers', to='classroom.Question'),
        ),
    ]
