# Generated by Django 3.0.5 on 2020-04-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_studentanswer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='quiz',
        ),
    ]
