# Generated by Django 3.0.5 on 2020-04-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_answer_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
