# Generated by Django 3.0.5 on 2020-04-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_quiz_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
