# Generated by Django 3.0.5 on 2020-04-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_auto_20200423_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='counter',
            field=models.FloatField(null=True),
        ),
    ]
