# Generated by Django 3.0.5 on 2020-06-10 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0020_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='is_responsable_de', to='classroom.Subject'),
            preserve_default=False,
        ),
    ]
