# Generated by Django 3.0.5 on 2020-06-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0021_teacher_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='groupe',
        ),
    ]
