# Generated by Django 3.0.5 on 2020-06-12 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0022_remove_subject_groupe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='student',
        ),
    ]
