# Generated by Django 3.0.5 on 2020-06-12 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0023_remove_studentanswer_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='classroom.Student'),
            preserve_default=False,
        ),
    ]
