# Generated by Django 3.0.5 on 2020-06-12 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0024_studentanswer_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='student',
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='classroom.Question'),
        ),
    ]
