# Generated by Django 3.0.5 on 2020-06-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0026_auto_20200612_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='answer_text',
            field=models.CharField(default=1, max_length=150, verbose_name='Reponse'),
            preserve_default=False,
        ),
    ]
