# Generated by Django 3.0.4 on 2020-06-14 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0028_auto_20200612_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='answer',
            field=models.CharField(max_length=2048),
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key1', models.CharField(max_length=2048)),
                ('key2', models.CharField(max_length=2048)),
                ('partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partie', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
