# Generated by Django 3.0.4 on 2020-06-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0029_auto_20200614_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='key2',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
