# Generated by Django 3.0.5 on 2020-06-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0031_quiz_results_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_deleguer',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='responsable_ready',
            field=models.CharField(default='', max_length=20),
        ),
    ]
