# Generated by Django 3.0.5 on 2020-06-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0032_auto_20200620_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='is_deleguer',
            new_name='deleguer_ready',
        ),
    ]
