# Generated by Django 3.0.7 on 2020-06-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0035_secret_ref_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='ref_quiz',
        ),
    ]
