# Generated by Django 3.0.7 on 2020-06-24 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0038_auto_20200622_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_sp', to='classroom.Subject')),
            ],
        ),
    ]
